### ISSUE TITLE
ChromeOptions headless

### ISSUE THREAD

**Issue by indy99** [durdyev/webdriverxx#14]
How can I start chrome as headless? In java it can be possible with ChromeOptions but I can't see that kind of function.

**Comment by sskcvqikf** [comment]
I think I am late, but you can do this with a function _CustomFromJson_. Browser options are passed to capabilities in json like that:
```
capabilities {
  browserName: 'chrome',

  chromeOptions: {
     args: [ "--headless", "--disable-gpu", "--window-size=800,600" ]
   }
}
```
Here is an example how you can pass them to Firefox.
```
picojson::value json;
std::string json_str(
            "{\"moz:firefoxOptions\":{"
                "\"args\":[\"--headless\"]"
            "}}"
    );
std::string err;
picojson::parse(json, json_str.begin(), json_str.end(), &err);
Capabilities caps;
CustomFromJson(json, caps);
WebDriver browser = Start(Firefox(caps));
```

**Comment by indy99** [comment]
I handled it another way. I will try your solutiıon. Thank you :)

**Comment by vega0** [comment]
its where to type when running **java -jar .\selenium-server-4.4.0.jar**

**Comment by vega0** [comment]
> I think I am late, but you can do this with a function _CustomFromJson_. Browser options are passed to capabilities in json like that:
> 
> ```
> capabilities {
>   browserName: 'chrome',
> 
>   chromeOptions: {
>      args: [ "--headless", "--disable-gpu", "--window-size=800,600" ]
>    }
> }
> ```
> 
> Here is an example how you can pass them to Firefox.
> 
> ```
> picojson::value json;
> std::string json_str(
>             "{\"moz:firefoxOptions\":{"
>                 "\"args\":[\"--headless\"]"
>             "}}"
>     );
> std::string err;
> picojson::parse(json, json_str.begin(), json_str.end(), &err);
> Capabilities caps;
> CustomFromJson(json, caps);
> WebDriver browser = Start(Firefox(caps));
> ```

post above
